import React from 'react';
import { Image, ImageStyle, StyleProp, StyleSheet, View, ViewStyle } from 'react-native';

/**
 * Intrinsic aspect ratio of the wordmark assets (980x400). Both variants are
 * cropped to the artwork itself, so this is the ratio of the *visible* logo and
 * not of a padded canvas. Callers set one dimension and the other is derived —
 * that is what keeps the logo identically proportioned on every screen.
 *
 * Both assets are generated by `scripts/build-wordmark.js`; if you re-run it with
 * a different OUT_HEIGHT, update this to match the dimensions it prints.
 */
const ASPECT_RATIO = 980 / 400;

const SOURCES = {
  // Wordmark lightened for dark surfaces (7.2:1 against the app background).
  onDark: require('../../assets/logo-wordmark-ondark.png'),
  // Original brand colours — only legible on white/light surfaces.
  brand: require('../../assets/logo-wordmark.png'),
} as const;

type Props = {
  /** Preferred control — width is derived from it. */
  height?: number;
  /** Used only when `height` is omitted. */
  width?: number;
  /** `onDark` (default) for app surfaces, `brand` for light backgrounds. */
  variant?: keyof typeof SOURCES;
  style?: StyleProp<ViewStyle>;
  imageStyle?: StyleProp<ImageStyle>;
};

const DEFAULT_HEIGHT = 40;

export default function BrandLogo({
  height,
  width,
  variant = 'onDark',
  style,
  imageStyle,
}: Props) {
  const h = height ?? (width != null ? width / ASPECT_RATIO : DEFAULT_HEIGHT);
  const w = h * ASPECT_RATIO;

  return (
    <View style={[{ width: w, height: h }, style]}>
      <Image
        source={SOURCES[variant]}
        resizeMode="contain"
        accessible
        accessibilityRole="image"
        accessibilityLabel="my prediction"
        style={[styles.image, imageStyle]}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  image: {
    width: '100%',
    height: '100%',
  },
});
